### ISSUE TITLE
error Couldn't find package "@bridged.xyz/design-sdk@0.1.0" required by "figma@0.1.0" on the "npm" registry

### ISSUE THREAD

**Issue by agus-tin** [bridgedxyz/assistant#24]
When I'm trying "yarn install" on a Windows 10, I'm getting the following error:

error Couldn't find package "@bridged.xyz/design-sdk@0.1.0" required by "figma@0.1.0" on the "npm" registry.

**Comment by softmarshmallow** [comment]
@agus-tin this project uses yarn workspace and gitsubmodules as noticed on README.

did you run git clone with `--recurse-submodules`?

**Comment by magestik247** [comment]
I have the same issue and I did what you said
I'm using W10, x64

**Comment by softmarshmallow** [comment]
referencing. https://github.com/bridgedxyz/assistant/issues/32
