### ISSUE TITLE
Error: Command failed, Error: Cannot find module...

### ISSUE THREAD

**Issue by magestik247** [bridgedxyz/assistant#32]
When I'm trying "yarn install" on a W 10, x64 I'm getting the following error:

error \assistant\node_modules\@reflect.bridged.xyz\uiutils: Command failed.
Exit code: 1
Command: tsc
Arguments:
Directory: \assistant\node_modules\@reflect.bridged.xyz\uiutils
Output:
internal/modules/cjs/loader.js:883
  throw err;

Error: assistant\node_modules\node_modules\typescript\bin\tsc'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {

**Comment by softmarshmallow** [comment]
I'm not familiar with windows environment, But fresh clone works for me.
Assuming that error is related to post-install problem, i'll try to fix it and notify you. meanwhile, may i ask when your clone was? the below is based on (https://github.com/bridgedxyz/assistant/commit/10fa683dd8f1c4a6cc09306848b2ba651163d007) (current latest master)

```
cd assistant 
 softmarshmallow@MacBook-Pro-4  ~/Downloads/test/assistant   master  yarn
yarn install v1.22.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
warning Pattern ["@types/node@latest"] is trying to unpack in the same destination "/Users/softmarshmallow/Library/Caches/Yarn/v6/npm-@types-node-14.14.7-8ea1e8f8eae2430cf440564b98c6dfce1ec5945d-integrity/node_modules/@types/node" as pattern ["@types/node@^14.14.5","@types/node@^14.11.2","@types/node@^14.11.8","@types/node@*","@types/node@*","@types/node@*","@types/node@*","@types/node@*","@types/node@*","@types/node@*","@types/node@*","@types/node@*","@types/node@*","@types/node@*","@types/node@*","@types/node@*","@types/node@*","@types/node@*","@types/node@*","@types/node@*","@types/node@*"]. This could result in non-deterministic behavior, skipping.
warning sketch@0.1.0: The engine "sketch" appears to be invalid.
[3/4] 🔗  Linking dependencies...
warning "workspace-aggregator-47ba093e-e51c-4dd5-864a-42dfc466698f > figma > pug-loader@2.4.0" has incorrect peer dependency "pug@^2.0.0".
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
✨  Done in 41.98s.
```

**Comment by softmarshmallow** [comment]
@magestik247 try this. it may work
https://github.com/bridgedxyz/assistant/commit/86c4c8cc42f8d80ffa4080eac41889432cee9c58

**Comment by magestik247** [comment]
still doesn't work

**Comment by softmarshmallow** [comment]
@magestik247  Can you give me your full log?

and also the result of `tree` command on repo root

**Comment by softmarshmallow** [comment]
Stale, Closing.
