### ISSUE TITLE
Constraints  Left&Right and Top&Bottom not work well 

### ISSUE THREAD

**Issue by taeilyoon** [bridgedxyz/assistant#49]
<img width="377" alt="스크린샷 2020-12-19 23 44 59" src="https://user-images.githubusercontent.com/23698016/102692045-36435300-4254-11eb-92f6-4135595d90cc.png">
<img width="228" alt="스크린샷 2020-12-19 23 45 09" src="https://user-images.githubusercontent.com/23698016/102692051-3c393400-4254-11eb-8ece-6dad7398c42f.png">

i think it's code it, should be 
```
          Padding(
            padding: const EdgeInsets.only(left : 36, right: 36),
            child: Container(
              height: 103,
              decoration: BoxDecoration(
                color: Color(
                  0xffc4c4c4,
                ),
              ),
            ),
          )
```

when Left&Right, Target's padding value should be fixed and stretch it.

**Comment by taeilyoon** [comment]
duplacate myself omg

**Comment by softmarshmallow** [comment]
duplicate of https://github.com/bridgedxyz/assistant/issues/37
